#-------------------------------
# General Site Settings
title: Pokke
logo: logo.png
description: Enjoy Pokke!
favicon: favicon.ico

#-------------------------------
# Contact links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/

