#-------------------------------
# General Site Settings
title: Pokke
logo: logo.png
description: Pokke is awesome service! Enjoy Pokke.
favicon: favicon.ico

#-------------------------------
# Contact links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/

